name: Run getinfo Script

on:
  push:
    # branches:
    #   - main  # Cambia esto por el nombre de tu rama principal si es diferente
  schedule:
    #  - cron: '0 6,12,15,18,21,0 * * *'  # Ejecuta el flujo de trabajo cada 30 minutos
    # - cron: '*/30 * * * *'
    - cron: '0 */3 * * *'
permissions:
      contents: write
      pull-requests: write

jobs:
  run-getinfo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.16.1'  # Asegúrate de usar una versión compatible con tu proyecto
      - name: Install dependencies
        run: npm ci
      - name: Run getinfo scriptt
        run: npm run getinfo
      - name: Add and commit changes
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add .
          git commit -m "Generate file via GitHub Action"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: main